apiVersion: corporate.io/v1alpha1
kind: SecureBucket
metadata:
  name: client-intelligent-platform-storage
spec:
  parameters:
    region: ap-northeast-1
    enforceEncryption: true
    publicAccessBlock: true
  compositionRef:
    # プラットフォーム側で定義されたCompositionにより、AWSならS3、GCPならGCSへ自動マッピングされる
    name: secure-s3-bucket-provider
